#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*               linuxserver/habridge                 *
*                                                    *
*    https://hub.docker.com/r/linuxserver/habridge   *
*                                                    *
*   https://github.com/linuxserver/docker-habridge   *
*                                                    *
*                                                    *
*                                                    *
******************************************************'
